spring:
  profiles:
    active: default,local
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}/${PGDATABASE:postgres}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}

custom:
  kafka:
    group: spring-boot-api
    topic:
      chat: chat-message